name: Slither

on: [push, pull_request]


jobs:
  slither:
    name: Slither Analysis
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['12.x']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: npm install, build, and test
        run: |
          npm install
          npm run compile
      - name: Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache pip
        uses: actions/cache@v2
        with: 
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install node dependencies
        run: yarn
      - name: Install slither
        run: |
          python -m pip install --upgrade pip
          pip3 install slither-analyzer
      - name: Install solc
        run: >
          sudo wget -O /usr/bin/solc
          https://github.com/ethereum/solidity/releases/download/v0.7.0/solc-static-linux
          sudo chmod +x /usr/bin/solc
      - name: Run slither
        run: slither .
